FROM grafana/grafana:8.1.5
RUN grafana-cli plugins install vonage-status-panel 
RUN grafana-cli plugins install snuids-trafficlights-panel 
RUN grafana-cli plugins install grafana-piechart-panel 
RUN grafana-cli plugins install jdbranham-diagram-panel
